name: C/C++ Linter
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches: [ main ] # Triggers on PRs targeting the main branch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run cpp-linter
      uses: cpp-linter/cpp-linter-action@v2
      id: linter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for posting comments
      with:
        style: 'file' # Use the .clang-format config file
        tidy-checks: '' # Use the .clang-tidy config file
        # Only 'update' a single comment in a pull request thread
        thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
    - name: Fail fast?!
      if: steps.linter.outputs.checks-failed > 0
      run: exit 1
